import Header from '@/components/header/header';
import './styles/globals.scss';
import { Roboto } from 'next/font/google'; // 일반 구글서버에서 가져온 폰트는 최적화가 되어있지 않아 같은 폰트임에도 용량차이가 있음

const roboto = Roboto({
	weight: '400',
	subsets: ['latin'],
	display: 'swap',
	preload: true,
	variable: '--font-roboto',
});

export const metadata = {
	title: '메인페이지',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			{/* 아래처럼 직접 변수명 등록 설정시 해당 JSX요소 안쪽에서는 css에서 등록된 변수명으로 폰트 설정 가능 */}
			<body className={`wrap $(roboto.variable)`}>
				<Header />
				<h1>No Google Font</h1>
				<h1>Google Font</h1>
				{children}
			</body>
		</html>
	);
}

/*
	Next 에서의 기능별 컴포넌트 구분
	-page Component: 페이지로 출력될 틀 컴포넌트(about/page.jsx, gallery/page.jsx 같은 것들)
		+ 따로 설정을 하지 않으면 기본적으로 Server에서 동작되서 prepage로 사전 렌더링

	-Partial Component: 페이지 안쪽에서 호출되면서 부분적인 UI나 기능을 담당하는 컴포넌트 (Compnents>header.jsx, components>popup.jsx 같은 것들)
*/
